### ISSUE TITLE
Run Time Estimation

### ISSUE THREAD

**Issue by XiaohanYa** [vdobrovolskii/wl-coref#1]
Hi, 
I just came across your paper. It is really impressive that you can lower the complexity to O(n^2). I want to try this model on my clusters. Would you mind telling me what devices you used and how long it took for your machine to run? Thank you so much!

**Comment by vdobrovolskii** [comment]
Hi, thanks for your interest!
Inference on OntoNotes development set took 32 seconds/2.9 GiB on nVidia Quadro RTX 8000, training took 5 hours on the same machine. You can find more details in [the paper](https://arxiv.org/abs/2109.04127), section 4.3.
