### ISSUE TITLE
About JOSHI-REPLICA pytorch version

### ISSUE THREAD

**Issue by sophiayyya** [vdobrovolskii/wl-coref#11]
Hi,

Which code did you use in the reimplementation of Joshi et al. pytorch version? Thanks

**Comment by vdobrovolskii** [comment]
Hi! This repo used to be this replica, but as the commits were squashed together before uploading, you can't find it on github. If you specifically need my reimplementation, I could find a local commit and send it to you. If you just need a pytorch version of the model by Joshi et al., I suggest you take a look at this repo: https://github.com/emorynlp/coref-hoi (SpanBERT + Attended Antecedent is the one).

**Comment by sophiayyya** [comment]
> 

Thank you for your quick reply! 
I tried your suggested repo but I only get about avg F1 78.1 on test dataset. Even when I use Provided trained models, I cannot get the correct result. Did you get the reported result? Maybe there are some mistake of my data?

**Comment by vdobrovolskii** [comment]
My guess is that you are probably better off asking this question there :)

I have not run the SpanBERT + AA model, but the results of EE and no-HOI models were close to the ones reported in the paper.

**Comment by sophiayyya** [comment]
> 

Ok. Thanks for answering. I will close this issue:)
