### ISSUE TITLE
DeBERTa

### ISSUE THREAD

**Issue by mhillebrand** [vdobrovolskii/wl-coref#14]
Have you considered training a wl-coref model using Microsoft's new [DeBERTa-v3-large](https://huggingface.co/microsoft/deberta-v3-large)?

**Comment by mhillebrand** [comment]
I would do it myself, but I really don't want to spend $27,000 for the OntoNotes 5.0 dataset. Ack!

**Comment by vdobrovolskii** [comment]
Hi, @mhillebrand !

I have considered trying that indeed, but I haven't had time to do it yet. I will do it in the next few months, I guess.

And what do you mean you don't want to spend $27,000 for the dataset? Last time I checked OntoNotes 5.0 was free for non-commercial use :)
