### ISSUE TITLE
Question about the license

### ISSUE THREAD

**Issue by wendywtchang** [vdobrovolskii/wl-coref#18]
Hello,

Good morning! My name is Wentseng and I am an intern at mine&make GmbH in Stuttgart, Germany.

We want build a commercial appliction using coreference resolution model and we are interested in your wl-coref model. However, we could not find any license in this project. Would you mind that we evaluating and integrating your model and would you mind adding some licenses in your project?

Thank you very much in advance!

**Comment by vdobrovolskii** [comment]
Hi!

I will be glad if my research can be actually helpful for anyone, be it commercial or not, so feel free to use and modify everything you want and ask questions if needed. :) 

I'll add a license, thanks for the suggestion.

Best regards,
Vladimir
