### ISSUE TITLE
Meaning of head

### ISSUE THREAD

**Issue by poncelettheo** [vdobrovolskii/wl-coref#19]
Sorry to bother you but I wanted to know what was the meaning of the head file in `convert_to_jsonlines.py`. What does it represent ? How can I retreive it from an other dataset than ARRAU ?

**Comment by vdobrovolskii** [comment]
Hi!
Convert_to_jsonlines writes syntactic info into the resulting files (see [this issue](https://github.com/vdobrovolskii/wl-coref/issues/6) for more details):
```
pos:            List[str]              # word id to POS mapping
deprel:         List[str]              # word id to dependency relation mapping
head:           List[int]              # word id to head word id mapping, None for root
```

So, `head` will contain the id of a word that is a direct syntactic parent of a word. For instance, in `I am a doctor` the heads will be arranged like this:
```
word_id		word     head_id
-------------------------------- 
      0            I           1
      1           am        null
      2            a           3
      3       doctor           1
```
