### ISSUE TITLE
about the selection of the best model

### ISSUE THREAD

**Issue by leileilin** [vdobrovolskii/wl-coref#24]
Hello, I think the code of saving the model is only saved every epoch, and the optimal model is not saved. Will it be reduced when evaluating the performance of the test set?
thanks.

**Comment by vdobrovolskii** [comment]
What do you mean, the optimal model is not saved? All the models are saved, and the logs are there, so you are free to choose the one whose metrics you like

**Comment by leileilin** [comment]
> What do you mean, the optimal model is not saved? All the models are saved, and the logs are there, so you are free to choose the one whose metrics you like

Yeah, of course, you can select the model by checking the log, but I think it is not as convenient as saving the optimal model.

**Comment by vdobrovolskii** [comment]
Pull requests with that functionality are most welcome :)

**Comment by leileilin** [comment]
> Pull requests with that functionality are most welcome :)

i test with different models, the experimental results are basically similar.
