### ISSUE TITLE
about the data format

### ISSUE THREAD

**Issue by leileilin** [vdobrovolskii/wl-coref#25]
Hello, I'd like to ask you if you understand the data format of the rightmost coreference resolution of conll format data? Or is there any relevant documentation?
here is a example:
bc/cctv/00/cctv_0000   0   23         Hong   NNP         (NML*         -    -   -   Speaker#1    (GPE*      *      *             *            *            *   (23
what does "(23" mean?
Thank you.

**Comment by vdobrovolskii** [comment]
The data was distributed as part CoNLL-2012 shared task on coreference resolution, you will find the documentation there: https://cemantix.org/data/ontonotes.html

**Comment by leileilin** [comment]
> The data was distributed as part CoNLL-2012 shared task on coreference resolution, you will find the documentation there: https://cemantix.org/data/ontonotes.html

thanks.
