### ISSUE TITLE
about experiment on litbank dataset

### ISSUE THREAD

**Issue by leileilin** [vdobrovolskii/wl-coref#26]
Hello, the experimental results on the litbank dataset are very poor. I wonder if you have done experiments on this dataset?

**Comment by vdobrovolskii** [comment]
No

**Comment by leileilin** [comment]
> No

Okay, thanks

**Comment by ritwikmishra** [comment]
@leileilin litbank contains singleton mentions

The proposed method is not able to detect singleton mentions.

Can you share the results you got on the litbank dataset? Default params
