### ISSUE TITLE
some confusions about convert_to_head.py

### ISSUE THREAD

**Issue by leileilin** [vdobrovolskii/wl-coref#27]
Hello, I have a new question about convert_ to_ heads.py file, in which some span and clusters will be deleted.
Is this the case as follows?
In those cases "A" and "A & B" are different spans with the same head word, "A". 
In our implementation such cases were simply discarded from the training set, because they were few and we were able to perform well, even though we couldn't predict any of such cases during inference.
like u said in #2 
thanks.

**Comment by vdobrovolskii** [comment]
I am sorry, I don't quite understand your question.
Are you asking if what I said in [issue #2](https://github.com/vdobrovolskii/wl-coref/issues/2) is true? Yes, it is

**Comment by leileilin** [comment]
> I am sorry, I don't quite understand your question. Are you asking if what I said in [issue #2](https://github.com/vdobrovolskii/wl-coref/issues/2) is true? Yes, it is

I mean the deleted span and clusters in convert_to_head.py is the same as the above example i proposed?

**Comment by vdobrovolskii** [comment]
What example are you referring to?

**Comment by leileilin** [comment]
> In those cases "A" and "A & B" are different spans with the same head word, "A".
> In our implementation such cases were simply discarded from the training set, because they were few and we were able to perform well, even though we couldn't predict any of such cases during inference.

In those cases "A" and "A & B" are different spans with the same head word, "A".
In our implementation such cases were simply discarded from the training set, because they were few and we were able to perform well, even though we couldn't predict any of such cases during inference.
it is the example you refered to in #2 .

**Comment by vdobrovolskii** [comment]
But what do you want me to say? You are quoting me to myself, do I need to additionally confirm what I said is still true? Or what? 😆

**Comment by leileilin** [comment]
> But what do you want me to say? You are quoting me to myself, do I need to additionally confirm what I said is still true? Or what? 😆

what i want to say is the deleted span and clusters in convert_to_head.py is the same as the above example i proposed?
i know the example is true but the relationship between them is not certain for me. 😆

**Comment by vdobrovolskii** [comment]
You mean, is there any difference between deleting a span and deleting a cluster?
Or you are talking about the variables `deleted_spans` and `deleted_clusters` in `convert_to_heads.py`?

**Comment by leileilin** [comment]
> You mean, is there any difference between deleting a span and deleting a cluster? Or you are talking about the variables `deleted_spans` and `deleted_clusters` in `convert_to_heads.py`?

I mean, I don't know the basis for deleting span and clusters in convert_to_head.py? is the same as the example above?

**Comment by leileilin** [comment]
> > You mean, is there any difference between deleting a span and deleting a cluster? Or you are talking about the variables `deleted_spans` and `deleted_clusters` in `convert_to_heads.py`?
> 
> I mean, I don't know the basis for deleting span and clusters in convert_to_head.py? is the same as the example above?

simplly to say , according to what to delete span and cluster in convert_to_head.py?

**Comment by vdobrovolskii** [comment]
Yes, according to _that_ you would delete spans.
And then all the singleton clusters also get deleted.

**Comment by leileilin** [comment]
> Yes, according to _that_ you would delete spans. And then all the singleton clusters also get deleted.

in other words, if "A" and "A & B" are different spans with the same head word, "A". so "A & B" will be deleted.
right ?

**Comment by vdobrovolskii** [comment]
yes

**Comment by leileilin** [comment]
> yes

If I don't delete it, can I train with such a dataset?

**Comment by vdobrovolskii** [comment]
You can, but it will be suboptimal (you will have the same head point to differen spans in span predictor module). And you will need to merge unrelated clusters.
