### ISSUE TITLE
about how to predict with gold mention?

### ISSUE THREAD

**Issue by leileilin** [vdobrovolskii/wl-coref#28]
hey, sorry to bother u again,
i want to ask if i know mentions in a doc, how to predict with such gold mentions?
thanks.

**Comment by vdobrovolskii** [comment]
You can run the model as usual and then filter the results, removing unwanted mentions and adjusting mention boundaries as needed.

**Comment by leileilin** [comment]
> You can run the model as usual and then filter the results, removing unwanted mentions and adjusting mention boundaries as needed.

We know that the anaphora resolution model is generally composed of two modules: mention detection and mention pair detection, and the mention detection module is not abosolutely right.
so if i have gold mentions with a doc, the menthod above proposed by u is still get little mention detection error, so i want to pass gold mention representations to model for better performance.
thanks.

**Comment by vdobrovolskii** [comment]
A feature of this particular model is searching for coreference links between individual words and not pre-extracted mentions.
The mentions are extracted after the coreference has been resolved, using [span_predictor.py](https://github.com/vdobrovolskii/wl-coref/blob/master/coref/span_predictor.py)
