### ISSUE TITLE
inference using predict.py

### ISSUE THREAD

**Issue by ShahzebPurelogics** [vdobrovolskii/wl-coref#33]
i save a input.jsonlines file with this {
        "document_id": "tc_mydoc_001",
        "cased_words": ["Hi", "!", "Bye", "."],
        "sent_id": [0, 0, 1, 1]
}
Now when i run command  python predict.py roberta "input.jsonlines" "output.jsonlines" --weights "data/roberta_(e20_2021.05.02_01.16)_release.pt" 
using the weights downloaded from dropbox, it loads default config which gives errors maybe because it by default start training and when it gets no training file it gives error. 
Can you please give me details how to run inference using custom input using pretrained weights file downloaded from dropbox?

**Comment by vdobrovolskii** [comment]
Hi! Try this solution:
https://github.com/vdobrovolskii/wl-coref/issues/13#issuecomment-1044694236
