### ISSUE TITLE
Better accuracy with XLnet

### ISSUE THREAD

**Issue by LifeIsStrange** [vdobrovolskii/wl-coref#34]
@vdobrovolskii
Hi,
I think you would beat the state of the art once again on coreference resolution by switching your Roberta with [XLnet](https://huggingface.co/docs/transformers/model_doc/xlnet).
Xlnet consistently outperform Roberta and often significantly.

Thanks for your hard work.

**Comment by vdobrovolskii** [comment]
Thank you for your suggestion!

**Comment by LifeIsStrange** [comment]
send me an update if you try that approach :)
There is also the topic of next gen optimizers/activation functions
(mish, lookahead, gradient centralization, etc https://github.com/lessw2020/Ranger21)

**Comment by LifeIsStrange** [comment]
For example I recommended XLnet to a researcher that had the SOTA in dependency parsing and it worked, he outperformed his previous result (BERT) and is still to this day the #1 SOTA on pen treebank
