### ISSUE TITLE
continue training from checkpoint?

### ISSUE THREAD

**Issue by Zoeyyao27** [vdobrovolskii/wl-coref#35]
Is there a way to continue training from the last model

**Comment by vdobrovolskii** [comment]
To actually continue, you would need the saved optimizer states, which were removed to make the weights file smaller. But it should be possible to initialize the weights of the model using the pretrained weights and then start the training

**Comment by Zoeyyao27** [comment]
> To actually continue, you would need the saved optimizer states, which were removed to make the weights file smaller. But it should be possible to initialize the weights of the model using the pretrained weights and then start the training

Thank you！ I actually managed to continue from saved checkpoint. But according to your code in https://github.com/vdobrovolskii/wl-coref/blob/96b3d5e50367b253cafa81ea82ae39e44ca7fa46/coref/coref_model.py#L266
I assume the optimizer states have already been saved?

**Comment by vdobrovolskii** [comment]
They were originally, but then they were stripped from the state dict by a separate script to save space

**Comment by Zoeyyao27** [comment]
> 

Ha! I see. Thank you for your kind reply! Great work by the way! :)
