### ISSUE TITLE
What's the meaning of sent_id and part_id in this dataset?

### ISSUE THREAD

**Issue by wbqhb** [vdobrovolskii/wl-coref#5]
What's the meaning of sent_id and part_id in this dataset?

**Comment by vdobrovolskii** [comment]
Hi!

Part_id is used for debugging purposes, as there can be multiple documents of the same name and different part_id. Also, the expected conll output format contains the part_id column, so this information has to be preserved.

Sent_id is used in two places:
1. When splitting the document into windows of 512 subtokens max, we don't want to split [in the middle of a sentence](https://github.com/vdobrovolskii/wl-coref/blob/abd039d882f5a3c04f2867671502cbf9ab41970c/coref/bert.py#L34).
2. When predicting spans from head words, we only consider possible boundaries [within the same sentence](https://github.com/vdobrovolskii/wl-coref/blob/abd039d882f5a3c04f2867671502cbf9ab41970c/coref/span_predictor.py#L57).

**Comment by wbqhb** [comment]
Thank you for your reply.

**Comment by wbqhb** [comment]
Another question, I am a novice in pytorch. My single GPU memory is not enough. How to run this code in parallel with multi-gpus, please?

**Comment by vdobrovolskii** [comment]
Do you have memory issues when training or when evaluating?
How much GPU memory do you have?

I'm asking because there's no simple solution to run the code with multiple gpus, but depending on your needs, I could suggest some approaches that might be helpful.

**Comment by wbqhb** [comment]
I want to train your model by adding my idea, I have ten GPUs with 16GB memory.

<img width="566" alt="图片" src="https://user-images.githubusercontent.com/93148332/143794851-96c381be-40ed-411d-9a0a-fb9b09c791ac.png">


Actually, I don't know where to add this to your code.

**Comment by vdobrovolskii** [comment]
I would try wrapping model.bert and model.a_scorer in [this function](https://github.com/vdobrovolskii/wl-coref/blob/7844a358187f21f860707e277518ad80a6f2d989/coref/coref_model.py#L358). They are the most memory intensive modules on training.

Alternatively, you can place them on different devices (using .to method).

Another way would be to try and use [LMS](https://github.com/IBM/pytorch-large-model-support)

**Comment by wbqhb** [comment]
Thank you for your help. I will have a try.
