### ISSUE TITLE
Inference

### ISSUE THREAD

**Issue by ghost** [vdobrovolskii/wl-coref#7]
Hi Vlad,

Thank you for providing the code. I enjoyed reading your paper and would like to try your method out.

Can you please provide a minimal example of using wl-coref for inference? I'm having trouble figuring out how to extract the coreference relationship by feeding a paragraph to the model. Thank you.

**Comment by vdobrovolskii** [comment]
Hi! Thanks for your interest!

I've added [a simple prediction script](https://github.com/vdobrovolskii/wl-coref/blob/master/predict.py), which will, however, require some data preparation. The preparation process is described in the [README](https://github.com/vdobrovolskii/wl-coref#prediction). If you have any further questions, please let me know at once.
