### ISSUE TITLE
Are all models in Table 2 in their base version?

### ISSUE THREAD

**Issue by yhcc** [vdobrovolskii/wl-coref#8]
Thank you for your time, but are all models in Table 2(as depicted in the following) in their base version (it is quite surprise that the RoBERTa-base got 80.72, while RoBERTa large got 81.0)?
![8F3D3D34-5662-43B1-85FF-B75DBD81AA1F](https://user-images.githubusercontent.com/22529082/146571876-7a407fed-8302-4c2c-93bc-7176e34a2936.png)

**Comment by vdobrovolskii** [comment]
No, all the models are in their large versions. BCE stands for Binary Cross Entropy.

**Comment by yhcc** [comment]
Thanks for you timely reply. So, why this ``wl + RoBERTa'' is 80.72, while in Table 1, it is 81.0 ~

**Comment by vdobrovolskii** [comment]
Table 2 shows performance on the development set, Table 1 uses the test set.

**Comment by yhcc** [comment]
Sorry for this silly question. But for my reproduction, your model usually gets higher performance in the development set. The highest performance I got in the development set is about 81.6. Thanks again for your answering, I will close this issue.

**Comment by vdobrovolskii** [comment]
Well, it depends heavily on the initialization. I used the same random seed for all my experiments, probably there is a better one out there :)
